### ISSUE TITLE
How do you use it?

### ISSUE THREAD

**Issue by dougyk1000** [Prashanth-365/Aviator-Predictor-Project#1]
I have no idea how to use the codes, can u be so kind as to show me the steps

**Comment by Prashanth-365** [comment]
I have updated the README.md file, you can refer that
if you have any questions please feel free to ask

**Comment by dougyk1000** [comment]
> I have updated the README.md file, you can refer that if you have any questions please feel free to ask

Thanks, I've tried running the main.py file but it says there's a missing file
![Uploading IMG_20241202_200811.jpg…]()

**Comment by dougyk1000** [comment]
There's a missing file

**Comment by Prashanth-365** [comment]
I have downloaded and run the same code but i didn't get anything like that
try changing webcam_id = 1 to webcam_id = 0 in main.py line 11

you might get something like this below

Image saved as ./dataset/Captured_image.png
[ WARN:1@6.200] global cap_msmf.cpp:488 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -1072873851
random text 

4
random text 
 count =  4
count =  0 []
Image Error! - Couldn't scan the image properly

please ignore that, it is not an issue.

If you are getting this at the end.
"C - capture image from screen
        S - To scan multiple images from the folder
        A - To arrange and formulate dataSet
        I - To predict instantly
        or input value manually
        close - To stop the program
        Select what action you need to perform:   "
then the code is working properly, then go ahead and enter the multiplier value.

**Comment by dougyk1000** [comment]
Thanks again but it keeps saying there is a missing file. It says so below:

ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by Prashanth-365** [comment]
This might be issue with OpenCV library
Try reinstalling the package
Take help of chatgpt
pip install opencv-python

If you are still facing issue, share me the screenshots of your code editor showing all files and the output screen

**Comment by dougyk1000** [comment]
Sorry but it's still not working
![IMG_20241206_175201](https://github.com/user-attachments/assets/d69d549b-20c3-41e2-895d-2b89e3c66626)
